defaults:
    - settings: vfine
    - _self_

n_steps: ${settings.n_steps}  
output_save_freq: 1000

# other constraints
friction_coeff: ${settings.friction_coeff}
temperature_kelvin: ${settings.temperature_kelvin}
timestep_femtoseconds: ${settings.timestep_femtoseconds}

# inputs
base_fld: protein-ligand-data/strep-biotin
device: CUDA
protein_pdb: ${base_fld}/protein.pdb
fix_protein_pdb: True
fixed_protein_pdb: ${base_fld}/protein_fixed.pdb
ligand_sdfs: 
    - ${base_fld}/BTN.sdf
outputpdb: simulation-results
_outputurl: ${base_fld}/${outputpdb}.pdb
_outputlog: ${base_fld}/${outputpdb}.log