defaults:
    - settings: vcoarse
    - _self_

n_iterations: ${settings.n_iterations} 
n_steps_per_iterations: ${settings.n_steps_per_iterations} 
min_energy_iterations: ${settings.min_energy_iterations} 
output_save_freq: ${settings.output_save_freq} 

# other constraints
friction_coeff: ${settings.friction_coeff}
temperature_kelvin: ${settings.temperature_kelvin}
n_lambda_states: ${settings.n_lambda_states}
pressure_bar: ${settings.pressure_bar}
timestep_femtoseconds: ${settings.timestep_femtoseconds}

# inputs
base_fld: protein-ligand-data/lysozyme-benzene
device: CUDA
protein_pdb: ${base_fld}/protein.pdb
fix_protein_pdb: True
fixed_protein_pdb: ${base_fld}/protein_fixed.pdb
ligand_sdfs: 
    - ${base_fld}/BNZ.sdf
    - ${base_fld}/EPE.sdf
outputfld: ${base_fld}/simulation-results-full
tsv_out: ${base_fld}/free_energy_results.tsv
